language: java
jdk:
  - oraclejdk7
env:
  global:
    secure: "d73adfc8af68c19aadab818670d3999ed4ce75cd"
    
before_script: 
  - mkdir $HOME/artifacts
  - cd src

script: 
  - javac -g CheckersMove.java  
  - javac -g CheckersData.java  
  - javac -g CheckersCanvas.java  
  - javac -g Checkers.java  
